language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: serginc
  password:
    secure: l3dj0ZIwnxPCQT0gm72Yl6ljusDju1Q1DXC6pNR8DGpRi9uVzjjv4Ntpv3JnLjlknZEkjTAzJmLpYnEy8qjG76sVEtBCHzdFJOpjF+B1Sjjp8bBkaONF3cYW6Q3MnbODj0Rj0uhX4m7sKoJ+5W8qirfOSmCF6O7N+G4C4FFJyKODo56b9ZtxrzK95+oh3V5ir26F09WQbFXw9asP+kJnVbEOs72BDOtAx06dGEypGCkAWbubey2AwDGwBI3gQl1AT1rFJ6WdU8LmhE6k4pc0+SgMLVFiJbDB0C1sIYzQJBE47YowRSWYGlv2JGywjKRBRo4htm1axw5fKoM5bcGszH9HNhvStRXnlGmNhWgXurgLNW0xJCnEEBPtKHN03V2gwIqn+kYMCFeSFgCdhWzr4YKpxr8DWasZ+V25Wd5KbtWr1tJGPSZCO94RKeDpzLQAXwUUOm8jmpk3PgyilvuaeLdEL+VksxJocquijX6iL1kyeI5GGgUotXE56wtZa4e/Cm5iAfcjAOU9qKC7xjOjZE1BoIjNJwhIRzVb7DeoggYdfGYklP1cX1JNNVnS66nlSGJCFGEAzBN9DE8CzmAgJHOatP0XdoX2rkcyFfHcdKAEo/ZOSGyuh7J1amnbKVX1igDaqbu8tSFPanPz8fCs2pshnuYCXTefoGIIduEraCU=
  on:
    tags: true
    repo: serginc21/alphabacktest
    python: 3.8
